#!/bin/sh

set -e

# setup environment
export PATH="/usr/share/rbenv/shims:$PATH"
export RBENV_VERSION="2.0.0-github6"

# write some debug info
ruby -v
echo "hostname: $(hostname)"
echo "pwd: $(pwd)"
git --version

_buildscripts/bootstrap

bundle exec rake test
