#!/bin/sh

if ! _buildscripts/cibuild; then
    printf '%s\n' 'Build failed' >&2
    exit 1
fi

# Clean out the articles directory
rm -rf _site/articles

# Create the archive
rm -rf _release
mkdir _release
cp -r _site _release/github-training-kit
pushd _release
zip -r github-training-kit.zip github-training-kit/
popd
