#!/bin/sh

set -e
export CC=gcc

echo "==> Installing gem dependencies…"
bundle check --path vendor/gems 2>&1 > /dev/null || {
  bundle install --path vendor/gems --quiet
}

echo "==> Cloning into submodules"
git submodule init
git submodule update
