#!/bin/sh

set -e

# setup environment
export PATH="/usr/share/rbenv/shims:$PATH"

# write some debug info
ruby -v
echo "hostname: $(hostname)"
echo "pwd: $(pwd)"
git --version
echo "node: $(node --version)"
echo "npm: $(npm --version)"

script/bootstrap

bundle exec rake test

find ./_site -type d \( -name assets -o -name _javascript -o -name downloads \) -prune -o -name "*.html" -print >> ./script/list-of-files.txt
find ./_site/downloads -type d \( -name ar -o -name bn_BD -o -name de \) -prune -o -name "*.html" -print >> ./script/list-of-files.txt

bundle exec npm test
