#!/bin/sh

set -e

# setup environment
export PATH="/usr/share/rbenv/shims:$PATH"

# write some debug info
ruby -v
echo "hostname: $(hostname)"
echo "pwd: $(pwd)"
git --version
echo "node: $(node --version)"
echo "npm: $(npm --version)"

script/bootstrap

bundle exec rake test

find ./_site -type d \( -name assets -o -name _javascript -o -name _downloads/ar -o -name _downloads/bn_BD -o -name _downloads/de -o -name _downloads/es_ES -o -name _downloads/fr -o -name _downloads/it -o -name _downloads/ja -o -name _downloads/kr -o -name _downloads/pt_BR -o -name _downloads/pt_PT -o -name _downloads/sk -o -name _downloads/zh_CN \) -prune -o -name "*.html" -print >> ./script/list-of-files.txt

bundle exec npm test
