#!/bin/sh

set -e

# setup environment
export PATH="/usr/share/rbenv/shims:$PATH"

# write some debug info
ruby -v
echo "hostname: $(hostname)"
echo "pwd: $(pwd)"
git --version
echo "node: $(node --version)"
echo "npm: $(npm --version)"

script/bootstrap

bundle exec rake test

find _site -type f -name "*.html" >> ./script/list-of-files.txt

bundle exec npm test
